version: "3.3"
services:
  app:
    build:
      args:
        user: www-data
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: presentation-website
    container_name: voluntr-api-app
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ./:/var/www
    networks:
      - voluntr-api
  db:
      platform: linux/x86_64
      image: 'mysql:8.0.33'
      container_name: 'voluntr-api-db'
      ports:
          - '3308:3306'
      restart: unless-stopped
      environment:
          MYSQL_DATABASE: 'voluntr-api'
          MYSQL_ROOT_PASSWORD: 'voluntr-api'
          MYSQL_PASSWORD: 'voluntr-api'
          MYSQL_USER: 'voluntr-api'
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
      volumes:
          - 'voluntr-api-mysql:/var/lib/mysql'
      networks:
          - voluntr-api
  meilisearch:
      image: 'getmeili/meilisearch:latest'
      ports:
          - '7700:7700'
      volumes:
          - 'voluntr-api-meilisearch:/meili_data'
      networks:
          - voluntr-api
      healthcheck:
          test:
              - CMD
              - wget
              - '--no-verbose'
              - '--spider'
              - 'http://localhost:7700/health'
          retries: 3
          timeout: 5s

  nginx:
    image: nginx:alpine
    container_name: voluntr-api-nginx
    restart: unless-stopped
    ports:
      - 9020:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - voluntr-api

networks:
  voluntr-api:
    driver: bridge
volumes:
    voluntr-api-mysql:
        driver: local
    voluntr-api-meilisearch:
        driver: local
